### Citi Bike Data Clean Up
Three input files will accepted as input for the Citi Bike data anlaysis from the Citi Bike data site.  The input files are the following dates: 

* 2018-10-03
* 2018-11-07
* 2018-12-04

Clean up will include the following: 

* Read in all of the files and clean up the column names. 
* Concatenate the files together. 
* The files include a birth year for each of the renters.  The current age of each renter has been calculated and appended to the file.  
* Output the final file to a .csv file for input into the tableau workbook.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
from pandas import DataFrame
from pandas import Series

# Raw data file
file1 = "Resources/20181003-citibike-tripdata.csv"
file2 = "Resources/20181107-citibike-tripdata.csv"
file3 = "Resources/20181204-citibike-tripdata.csv"

In [2]:
# Read file 1 data and store in a pandas data frame
df1 = pd.read_csv(file1)
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1

In [3]:
# Read file 2 data and store in a pandas data frame
df2 = pd.read_csv(file2)
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,152,2018-10-01 07:44:41.4170,2018-10-01 07:47:14.2960,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,15302,Subscriber,1971,2
1,122,2018-10-01 08:50:05.4340,2018-10-01 08:52:08.2250,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29654,Subscriber,1973,1
2,211,2018-10-01 09:03:17.0640,2018-10-01 09:06:48.0940,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33621,Subscriber,1958,1
3,342,2018-10-01 10:13:07.0090,2018-10-01 10:18:49.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26266,Subscriber,1982,1
4,2976,2018-10-01 10:45:14.2800,2018-10-01 11:34:51.2610,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,27083,Customer,1969,0

In [4]:
# Read file 3 data and store in a pandas data frame
df3 = pd.read_csv(file3)
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1188,2018-11-01 06:32:27.5190,2018-11-01 06:52:15.9140,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33662,Customer,1969,0
1,278,2018-11-01 07:14:31.8680,2018-11-01 07:19:10.2610,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29254,Subscriber,1963,1
2,115,2018-11-01 07:33:17.1920,2018-11-01 07:35:12.2830,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33607,Subscriber,1966,1
3,155,2018-11-01 08:20:10.9320,2018-11-01 08:22:46.7050,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29222,Subscriber,1975,2
4,82,2018-11-01 08:35:02.7850,2018-11-01 08:36:25.1840,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29678,Subscriber,1975,1

In [5]:
# Clean up the column names on file 1 so when they are displayed on the Tableau workbook they will make sense. 
df1.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1

In [6]:
# Clean up the column names on file 2 so when they are displayed on the Tableau workbook they will make sense. 
df2.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,152,2018-10-01 07:44:41.4170,2018-10-01 07:47:14.2960,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,15302,Subscriber,1971,2
1,122,2018-10-01 08:50:05.4340,2018-10-01 08:52:08.2250,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29654,Subscriber,1973,1
2,211,2018-10-01 09:03:17.0640,2018-10-01 09:06:48.0940,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33621,Subscriber,1958,1
3,342,2018-10-01 10:13:07.0090,2018-10-01 10:18:49.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26266,Subscriber,1982,1
4,2976,2018-10-01 10:45:14.2800,2018-10-01 11:34:51.2610,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,27083,Customer,1969,0

In [7]:
# Clean up the column names on file 3 so when they are displayed on the Tableau workbook they will make sense. 
df3.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1188,2018-11-01 06:32:27.5190,2018-11-01 06:52:15.9140,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33662,Customer,1969,0
1,278,2018-11-01 07:14:31.8680,2018-11-01 07:19:10.2610,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29254,Subscriber,1963,1
2,115,2018-11-01 07:33:17.1920,2018-11-01 07:35:12.2830,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33607,Subscriber,1966,1
3,155,2018-11-01 08:20:10.9320,2018-11-01 08:22:46.7050,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29222,Subscriber,1975,2
4,82,2018-11-01 08:35:02.7850,2018-11-01 08:36:25.1840,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29678,Subscriber,1975,1

In [8]:
citi_df = pd.concat([df1, df2, df3])
citi_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1
5,497,2018-09-01 10:23:15.7840,2018-09-01 10:31:32.9800,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29569,Subscriber,1969,2
6,426,2018-09-01 10:49:48.2870,2018-09-01 10:56:54.3760,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,29497,Subscriber,1965,2
7,138,2018-09-01 11:01:00.9880,2018-09-01 11:03:19.2540,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26178,Subscriber,1987,1
8,280,2018-09-01 11:41:15.9230,2018-09-01 11:45:56.1620,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29459,Subscriber,1981,1
9,2026,2018-09-01 11:43:57.4740,2018-09-01 12:17:44.1050,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29434,Customer,1969,0
10,2020,2018-09-01 11:44:12.4460,2018-09-01 12:17:52.9200,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29127,Customer,1969,0
11,2088,2018-09-01 11:51:51.0010,2018-09-01 12:26:39.2900,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33619,Subscriber,1955,2
12,2068,2018-09-01 11:52:01.1640,2018-09-01 12:26:29.7340,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,26286,Subscriber,1956,1
13,818,2018-09-01 12:28:42.9140,2018-09-01 12:42:21.1310,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,26297,Subscriber,1991,1
14,222,2018-09-01 13:19:50.6720,2018-09-01 13:23:32.8860,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,29588,Subscriber,1987,1
15,2085,2018-09-01 14:40:55.9970,2018-09-01 15:15:41.9700,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29647,Customer,1999,2
16,255,2018-09-01 15:45:22.6160,2018-09-01 15:49:38.0690,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,33555,Subscriber,1990,1
17,288,2018-09-01 15:48:10.5320,2018-09-01 15:52:58.5340,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29676,Subscriber,1987,1
18,201,2018-09-01 16:22:45.4280,2018-09-01 16:26:07.2280,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,33613,Subscriber,1991,1
19,1168,2018-09-01 16:22:59.8210,2018-09-01 16:42:28.0350,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,33593,Subscriber,1990,1
20,1170,2018-09-01 16:23:09.0950,2018-09-01 16:42:39.3620,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,32077,Subscriber,1991,2
21,1196,2018-09-01 16:23:15.4640,2018-09-01 16:43:12.1850,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,16590,Subscriber,1990,1
22,203,2018-09-01 16:25:19.5680,2018-09-01 16:28:43.1160,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33674,Subscriber,1969,0
23,260,2018-09-01 17:16:36.0010,2018-09-01 17:20:56.5250,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,33635,Subscriber,1993,1
24,596,2018-09-01 17:30:48.1990,2018-09-01 17:40:44.7550,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,33608,Subscriber,1995,1
25,576,2018-09-01 17:40:52.5210,2018-09-01 17:50:28.8790,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,29519,Subscriber,1985,1
26,878,2018-09-01 17:40:54.2660,2018-09-01 17:55:33.1480,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,29250,Subscriber,1987,1
27,218,2018-09-01 17:42:06.1350,2018-09-01 17:45:44.3190,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29215,Subscriber,1990,1
28,379,2018-09-01 18:25:03.8390,2018-09-01 18:31:23.3760,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26310,Subscriber,1991,1
29,227,2018-09-01 18:25:52.3710,2018-09-01 18:29:40.1520,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,29484,Subscriber,1985,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24880,5179,2018-11-09 13:05:22.0440,2018-11-09 14:31:41.7210,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29674,Subscriber,1974,1
24881,1386,2018-11-09 14:33:59.1640,2018-11-09 14:57:05.2150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29674,Subscriber,1974,1
24882,16212,2018-11-12 12:58:18.9190,2018-11-12 17:28:31.2000,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,29677,Subscriber,1992,1
24883,604,2018-11-12 15:55:25.0370,2018-11-12 16:05:29.0630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29618,Subscriber,1991,2
24884,1197,2018-11-13 16:38:49.4210,2018-11-13 16:58:46.9170,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29582,Subscriber,1986,2
24885,1003,2018-11-14 06:23:56.6900,2018-11-14 06:40:40.5420,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29662,Subscriber,1977,1
24886,794,2018-11-14 16:13:19.6520,2018-11-14 16:26:34.4850,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29623,Subscriber,1986,2
24887,1336,2018-11-14 19:29:36.4350,2018-11-14 19:51:52.5900,3694,Jackson Square,40.711130,-74.078900,3202,Newport PATH,40.727224,-74.033759,29669,Customer,1989,1
24888,2517,2018-11-15 11:39:14.7350,2018-11-15 12:21:11.7570,3694,Jackson Square,40.711130,-74.078900,3192,Liberty Light Rail,40.711242,-74.055701,29494,Customer,1989,1
24889,597,2018-11-17 10:22:05.2810,2018-11-17 10:32:03.0190,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29441,Subscriber,1990,2
24890,1463,2018-11-17 14:39:55.2330,2018-11-17 15:04:18.3380,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29497,Subscriber,1988,2
24891,688,2018-11-17 18:33:03.6770,2018-11-17 18:44:31.6880,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29507,Subscriber,1991,2
24892,406,2018-11-18 13:04:14.7720,2018-11-18 13:11:01.0180,3694,Jackson Square,40.711130,-74.078900,3193,Lincoln Park,40.724605,-74.078406,29204,Subscriber,1990,2
24893,1405,2018-11-18 22:11:53.4960,2018-11-18 22:35:18.6370,3694,Jackson Square,40.711130,-74.078900,3220,5 Corners Library,40.734961,-74.059503,29244,Subscriber,1987,1
24894,673,2018-11-18 22:54:18.6150,2018-11-18 23:05:31.7600,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,29299,Customer,1998,2
24895,987,2018-11-20 06:27:14.2960,2018-11-20 06:43:41.6230,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29271,Subscriber,1977,1
24896,2023,2018-11-20 13:09:01.4580,2018-11-20 13:42:45.4240,3694,Jackson Square,40.711130,-74.078900,3184,Paulus Hook,40.714145,-74.033552,29652,Customer,1995,1
24897,943,2018-11-21 06:25:06.5540,2018-11-21 06:40:49.5850,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29458,Subscriber,1977,1
24898,872,2018-11-24 13:26:37.2970,2018-11-24 13:41:09.8250,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26193,Subscriber,1994,1
24899,673,2018-11-25 11:38:07.7060,2018-11-25 11:49:20.8900,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29439,Subscriber,1994,1
24900,1418,2018-11-26 09:55:15.2920,2018-11-26 10:18:54.0580,3694,Jackson Square,40.711130,-74.078900,3198,Heights Elevator,40.748716,-74.040443,29506,Customer,1987,1
24901,617,2018-11-26 10:24:41.1230,2018-11-26 10:34:58.5150,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26250,Subscriber,1994,1
24902,979,2018-11-26 22:09:13.7080,2018-11-26 22:25:32.7220,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29451,Customer,1987,1
24903,694,2018-11-27 12:06:57.5180,2018-11-27 12:18:32.5060,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29283,Subscriber,1994,1
24904,1013,2018-11-28 06:27:11.0670,2018-11-28 06:44:04.6710,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29538,Subscriber,1977,1
24905,734,2018-11-28 10:46:12.6640,2018-11-28 10:58:27.0750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26255,Subscriber,1994,1
24906,312,2018-11-28 19:52:40.1140,2018-11-28 19:57:52.9270,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29451,Subscriber,1957,1
24907,914,2018-11-29 10:20:57.7240,2018-11-29 10:36:12.0420,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,29610,Subscriber,1994,1
24908,2392,2018-11-29 17:28:24.1590,2018-11-29 18:08:16.8720,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29659,Subscriber,1994,1
24909,637,2018-11-30 12:00:10.4100,2018-11-30 12:10:48.0210,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29536,Subscriber,1994,1

## Age Calculation

* Subtract the birth year from the current year to determine the age of the renter.  Append the age to the record.

In [9]:
# Get Current Year
import datetime
now = datetime.datetime.now()

print("Current date and time: ")
print(now)

year = (now.year)
print("Current year: ")
print(year)

Current date and time:
2018-12-22 20:10:25.322887
Current year:
2018

In [10]:
# Get a list of columns for easy reference
citi_df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [11]:
# Extract "starttime", "start station id", "start station name", "usertype", "birth year" and "gender"
citi_df = citi_df.loc[:, ['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender']]
citi_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1
5,497,2018-09-01 10:23:15.7840,2018-09-01 10:31:32.9800,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29569,Subscriber,1969,2
6,426,2018-09-01 10:49:48.2870,2018-09-01 10:56:54.3760,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,29497,Subscriber,1965,2
7,138,2018-09-01 11:01:00.9880,2018-09-01 11:03:19.2540,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26178,Subscriber,1987,1
8,280,2018-09-01 11:41:15.9230,2018-09-01 11:45:56.1620,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29459,Subscriber,1981,1
9,2026,2018-09-01 11:43:57.4740,2018-09-01 12:17:44.1050,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29434,Customer,1969,0
10,2020,2018-09-01 11:44:12.4460,2018-09-01 12:17:52.9200,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29127,Customer,1969,0
11,2088,2018-09-01 11:51:51.0010,2018-09-01 12:26:39.2900,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33619,Subscriber,1955,2
12,2068,2018-09-01 11:52:01.1640,2018-09-01 12:26:29.7340,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,26286,Subscriber,1956,1
13,818,2018-09-01 12:28:42.9140,2018-09-01 12:42:21.1310,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,26297,Subscriber,1991,1
14,222,2018-09-01 13:19:50.6720,2018-09-01 13:23:32.8860,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,29588,Subscriber,1987,1
15,2085,2018-09-01 14:40:55.9970,2018-09-01 15:15:41.9700,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29647,Customer,1999,2
16,255,2018-09-01 15:45:22.6160,2018-09-01 15:49:38.0690,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,33555,Subscriber,1990,1
17,288,2018-09-01 15:48:10.5320,2018-09-01 15:52:58.5340,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29676,Subscriber,1987,1
18,201,2018-09-01 16:22:45.4280,2018-09-01 16:26:07.2280,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,33613,Subscriber,1991,1
19,1168,2018-09-01 16:22:59.8210,2018-09-01 16:42:28.0350,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,33593,Subscriber,1990,1
20,1170,2018-09-01 16:23:09.0950,2018-09-01 16:42:39.3620,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,32077,Subscriber,1991,2
21,1196,2018-09-01 16:23:15.4640,2018-09-01 16:43:12.1850,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,16590,Subscriber,1990,1
22,203,2018-09-01 16:25:19.5680,2018-09-01 16:28:43.1160,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33674,Subscriber,1969,0
23,260,2018-09-01 17:16:36.0010,2018-09-01 17:20:56.5250,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,33635,Subscriber,1993,1
24,596,2018-09-01 17:30:48.1990,2018-09-01 17:40:44.7550,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,33608,Subscriber,1995,1
25,576,2018-09-01 17:40:52.5210,2018-09-01 17:50:28.8790,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,29519,Subscriber,1985,1
26,878,2018-09-01 17:40:54.2660,2018-09-01 17:55:33.1480,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,29250,Subscriber,1987,1
27,218,2018-09-01 17:42:06.1350,2018-09-01 17:45:44.3190,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29215,Subscriber,1990,1
28,379,2018-09-01 18:25:03.8390,2018-09-01 18:31:23.3760,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26310,Subscriber,1991,1
29,227,2018-09-01 18:25:52.3710,2018-09-01 18:29:40.1520,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,29484,Subscriber,1985,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24880,5179,2018-11-09 13:05:22.0440,2018-11-09 14:31:41.7210,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29674,Subscriber,1974,1
24881,1386,2018-11-09 14:33:59.1640,2018-11-09 14:57:05.2150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29674,Subscriber,1974,1
24882,16212,2018-11-12 12:58:18.9190,2018-11-12 17:28:31.2000,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,29677,Subscriber,1992,1
24883,604,2018-11-12 15:55:25.0370,2018-11-12 16:05:29.0630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29618,Subscriber,1991,2
24884,1197,2018-11-13 16:38:49.4210,2018-11-13 16:58:46.9170,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29582,Subscriber,1986,2
24885,1003,2018-11-14 06:23:56.6900,2018-11-14 06:40:40.5420,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29662,Subscriber,1977,1
24886,794,2018-11-14 16:13:19.6520,2018-11-14 16:26:34.4850,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29623,Subscriber,1986,2
24887,1336,2018-11-14 19:29:36.4350,2018-11-14 19:51:52.5900,3694,Jackson Square,40.711130,-74.078900,3202,Newport PATH,40.727224,-74.033759,29669,Customer,1989,1
24888,2517,2018-11-15 11:39:14.7350,2018-11-15 12:21:11.7570,3694,Jackson Square,40.711130,-74.078900,3192,Liberty Light Rail,40.711242,-74.055701,29494,Customer,1989,1
24889,597,2018-11-17 10:22:05.2810,2018-11-17 10:32:03.0190,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29441,Subscriber,1990,2
24890,1463,2018-11-17 14:39:55.2330,2018-11-17 15:04:18.3380,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29497,Subscriber,1988,2
24891,688,2018-11-17 18:33:03.6770,2018-11-17 18:44:31.6880,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29507,Subscriber,1991,2
24892,406,2018-11-18 13:04:14.7720,2018-11-18 13:11:01.0180,3694,Jackson Square,40.711130,-74.078900,3193,Lincoln Park,40.724605,-74.078406,29204,Subscriber,1990,2
24893,1405,2018-11-18 22:11:53.4960,2018-11-18 22:35:18.6370,3694,Jackson Square,40.711130,-74.078900,3220,5 Corners Library,40.734961,-74.059503,29244,Subscriber,1987,1
24894,673,2018-11-18 22:54:18.6150,2018-11-18 23:05:31.7600,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,29299,Customer,1998,2
24895,987,2018-11-20 06:27:14.2960,2018-11-20 06:43:41.6230,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29271,Subscriber,1977,1
24896,2023,2018-11-20 13:09:01.4580,2018-11-20 13:42:45.4240,3694,Jackson Square,40.711130,-74.078900,3184,Paulus Hook,40.714145,-74.033552,29652,Customer,1995,1
24897,943,2018-11-21 06:25:06.5540,2018-11-21 06:40:49.5850,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29458,Subscriber,1977,1
24898,872,2018-11-24 13:26:37.2970,2018-11-24 13:41:09.8250,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26193,Subscriber,1994,1
24899,673,2018-11-25 11:38:07.7060,2018-11-25 11:49:20.8900,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29439,Subscriber,1994,1
24900,1418,2018-11-26 09:55:15.2920,2018-11-26 10:18:54.0580,3694,Jackson Square,40.711130,-74.078900,3198,Heights Elevator,40.748716,-74.040443,29506,Customer,1987,1
24901,617,2018-11-26 10:24:41.1230,2018-11-26 10:34:58.5150,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26250,Subscriber,1994,1
24902,979,2018-11-26 22:09:13.7080,2018-11-26 22:25:32.7220,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29451,Customer,1987,1
24903,694,2018-11-27 12:06:57.5180,2018-11-27 12:18:32.5060,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29283,Subscriber,1994,1
24904,1013,2018-11-28 06:27:11.0670,2018-11-28 06:44:04.6710,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29538,Subscriber,1977,1
24905,734,2018-11-28 10:46:12.6640,2018-11-28 10:58:27.0750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26255,Subscriber,1994,1
24906,312,2018-11-28 19:52:40.1140,2018-11-28 19:57:52.9270,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29451,Subscriber,1957,1
24907,914,2018-11-29 10:20:57.7240,2018-11-29 10:36:12.0420,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,29610,Subscriber,1994,1
24908,2392,2018-11-29 17:28:24.1590,2018-11-29 18:08:16.8720,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29659,Subscriber,1994,1
24909,637,2018-11-30 12:00:10.4100,2018-11-30 12:10:48.0210,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29536,Subscriber,1994,1

In [12]:
citi_df["age"] = (year - citi_df['birth year'])
citi_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1,34
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1,34
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1,24
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1,31
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1,33

In [13]:
citi_df.to_csv('Resources/citi_df.csv', sep = ',')